name: Publish Apollo Subgraph

inputs:
  graph-ref:
    required: true
  routing-url:
    required: true
  schema-path-or-url:
    required: true
  subgraph-name:
    required: true

runs:
  using: "composite"
  steps:
    - run: rover subgraph publish "${{inputs.graph-ref}}" --routing-url "${{inputs.routing-url}}" --schema "${{inputs.schema-path-or-url}}" --name ${{inputs.subgraph-name}}
      shell: bash